### ISSUE TITLE
部署问题==

### ISSUE THREAD

**Issue by BZBY** [ximinng/DiffSketcher#12]
我在docker 里运行遇到了问题。。。

(diffsketcher) root@c3180851e28d:/diffvg# python setup.py install
running install
/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing diffvg.egg-info/PKG-INFO
writing dependency_links to diffvg.egg-info/dependency_links.txt
writing requirements to diffvg.egg-info/requires.txt
writing top-level names to diffvg.egg-info/top_level.txt
reading manifest file 'diffvg.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'diffvg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/diffvg/setup.py", line 92, in <module>
    setup(name = 'diffvg',
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/diffvg/setup.py", line 31, in run
    super().run()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/diffsketcher/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/diffvg/setup.py", line 65, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/opt/conda/envs/diffsketcher/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['cmake', '/diffvg', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/diffvg/build/lib.linux-x86_64-cpython-310', '-DPYTHON_LIBRARY=/opt/conda/envs/diffsketcher/lib', '-DPYTHON_INCLUDE_PATH=/opt/conda/envs/diffsketcher/include/python3.10', '-DCMAKE_BUILD_TYPE=Release', '-DDIFFVG_CUDA=0']' returned non-zero exit status 1.

**Comment by ximinng** [comment]
hello BZBY,

Follow the steps in the installation method in README.

Best regards,
Ximing

**Comment by BZBY** [comment]
> hello BZBY,
> 
> Follow the steps in the installation method in README.
> 
> Best regards, Ximing

  I apologize for any inconvenience caused. Upon following the instructions in the `readme.md` , I encountered an error in `diffvg/setup.py`, line 39:
 
 ```
\diffvg\setup.py", line 39, in build_extension

    '-DPYTHON_LIBRARY=' + get_config_var('LIBDIR'),
TypeError: can only concatenate str (not "NoneType") to str

 ```
 
 I am not sure how to resolve this issue. Thank you for your patience.

**Comment by BZBY** [comment]
> hello BZBY,
> 
> Follow the steps in the installation method in README.
> 
> Best regards, Ximing

I try something.  try“'-DPYTHON_LIBRARY=D:\\Programm\\anconda\\envs\\diff112\\Lib',and use another vs2019 cmake,to solve 
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
fin,  -- Build files have been written .The problem seems to have been solved, I'll try running other content to see if I can generate an image.

**Comment by BZBY** [comment]
> hello BZBY,
> 
> Follow the steps in the installation method in README.
> 
> Best regards, Ximing

After testing in the Windows environment, I encountered numerous issues with the diffvg project, specifically an "ImportError: DLL load failed while importing diffvg". I have been unable to find a definitive solution, and it seems that there haven't been recent responses to issues on the DiffVG project.

In light of this, I would appreciate it if you could, when you have the time, create a Docker image or package your Python Conda environment. I believe this could potentially resolve many of the issues I'm facing.
